set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_OT/FFN_BRAM_OT/FFN_BRAM_OT_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_OT/FFN_BRAM_OT/FFN_BRAM_OT_in_context.xdc id:1 order:EARLY scoped_inst:FFN_top_inst/ot_top_inst/ot_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/MULT_3_STAGE_32X32/MULT_3_STAGE_32X32/MULT_3_STAGE_32X32_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/MULT_3_STAGE_32X32/MULT_3_STAGE_32X32/MULT_3_STAGE_32X32_in_context.xdc id:2 order:EARLY scoped_inst:FFN_top_inst/pe_top_inst/blkpe_r0/q0_m0/mult_3_stage_inst1} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/MULT_2_STAGE_32X16/MULT_2_STAGE_32X16/MULT_2_STAGE_32X16_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/MULT_2_STAGE_32X16/MULT_2_STAGE_32X16/MULT_2_STAGE_32X16_in_context.xdc id:3 order:EARLY scoped_inst:FFN_top_inst/pe_top_inst/blkpe_r0/q0_m0/mult_2_stage_inst0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_BIAS/FFN_BRAM_BIAS/FFN_BRAM_BIAS_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_BIAS/FFN_BRAM_BIAS/FFN_BRAM_BIAS_in_context.xdc id:4 order:EARLY scoped_inst:FFN_top_inst/bias_top_inst/bias_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:5 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[0].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:6 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[1].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:7 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[2].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:8 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[3].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:9 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[4].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:10 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[5].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:11 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[6].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:12 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[7].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:13 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[8].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:14 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[9].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:15 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[10].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:16 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[11].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:17 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[12].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:18 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[13].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:19 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[14].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_KER/FFN_BRAM_KER/FFN_BRAM_KER_in_context.xdc id:20 order:EARLY scoped_inst:{FFN_top_inst/ker_top_inst/ker_bank[15].ker_inst}} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_IF/FFN_BRAM_IF/FFN_BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/FFN_BRAM_IF/FFN_BRAM_IF/FFN_BRAM_IF_in_context.xdc id:21 order:EARLY scoped_inst:FFN_top_inst/if_top_inst/if_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/DW_sqrt/DW_sqrt/DW_sqrt_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/DW_sqrt/DW_sqrt/DW_sqrt_in_context.xdc id:22 order:EARLY scoped_inst:dut_addnorm/u_sqrt} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_OT/BRAM_OT/BRAM_OT_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_OT/BRAM_OT/BRAM_OT_in_context.xdc id:23 order:EARLY scoped_inst:SA_top_inst/ota01/otbf_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_OT/BRAM_OT/BRAM_OT_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_OT/BRAM_OT/BRAM_OT_in_context.xdc id:24 order:EARLY scoped_inst:SA_top_inst/ota01/otbf_1} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_OT/BRAM_OT/BRAM_OT_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_OT/BRAM_OT/BRAM_OT_in_context.xdc id:25 order:EARLY scoped_inst:SA_top_inst/ota01/otbf_r1_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_OT/BRAM_OT/BRAM_OT_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_OT/BRAM_OT/BRAM_OT_in_context.xdc id:26 order:EARLY scoped_inst:SA_top_inst/ota01/otbf_r1_1} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_BIAS/BRAM_BIAS/BRAM_BIAS_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_BIAS/BRAM_BIAS/BRAM_BIAS_in_context.xdc id:27 order:EARLY scoped_inst:SA_top_inst/bia01/bias_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc id:28 order:EARLY scoped_inst:SA_top_inst/kea01/ker_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc id:29 order:EARLY scoped_inst:SA_top_inst/kea01/ker_1} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc id:30 order:EARLY scoped_inst:SA_top_inst/kea01/ker_2} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc id:31 order:EARLY scoped_inst:SA_top_inst/kea01/ker_3} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc id:32 order:EARLY scoped_inst:SA_top_inst/kea01/ker_4} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc id:33 order:EARLY scoped_inst:SA_top_inst/kea01/ker_5} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc id:34 order:EARLY scoped_inst:SA_top_inst/kea01/ker_6} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_KER/BRAM_KER/BRAM_KER_in_context.xdc id:35 order:EARLY scoped_inst:SA_top_inst/kea01/ker_7} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:36 order:EARLY scoped_inst:SA_top_inst/ifa01/if0bA} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:37 order:EARLY scoped_inst:SA_top_inst/ifa01/if0bB} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:38 order:EARLY scoped_inst:SA_top_inst/ifa01/if1bA} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:39 order:EARLY scoped_inst:SA_top_inst/ifa01/if1bB} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:40 order:EARLY scoped_inst:SA_top_inst/ifa01/if2bA} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:41 order:EARLY scoped_inst:SA_top_inst/ifa01/if2bB} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:42 order:EARLY scoped_inst:SA_top_inst/ifa01/if3bA} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:43 order:EARLY scoped_inst:SA_top_inst/ifa01/if3bB} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:44 order:EARLY scoped_inst:SA_top_inst/ifa01/if4bA} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:45 order:EARLY scoped_inst:SA_top_inst/ifa01/if4bB} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:46 order:EARLY scoped_inst:SA_top_inst/ifa01/if5bA} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:47 order:EARLY scoped_inst:SA_top_inst/ifa01/if5bB} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:48 order:EARLY scoped_inst:SA_top_inst/ifa01/if6bA} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:49 order:EARLY scoped_inst:SA_top_inst/ifa01/if6bB} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:50 order:EARLY scoped_inst:SA_top_inst/ifa01/if7bA} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc rfile:../../../vivado/build/Transformer_IP/Transformer_IP.srcs/sources_1/ip/BRAM_IF/BRAM_IF/BRAM_IF_in_context.xdc id:51 order:EARLY scoped_inst:SA_top_inst/ifa01/if7bB} [current_design]
current_instance FFN_top_inst/ot_top_inst/ot_0
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells FFN_top_inst/ot_top_inst/ot_0]
current_instance FFN_top_inst/pe_top_inst/blkpe_r0/q0_m0/mult_3_stage_inst1
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_ports -scoped_to_current_instance CLK]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells FFN_top_inst/pe_top_inst/blkpe_r0/q0_m0/mult_3_stage_inst1]
current_instance FFN_top_inst/pe_top_inst/blkpe_r0/q0_m0/mult_2_stage_inst0
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_ports -scoped_to_current_instance CLK]
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells FFN_top_inst/pe_top_inst/blkpe_r0/q0_m0/mult_2_stage_inst0]
current_instance FFN_top_inst/bias_top_inst/bias_0
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells FFN_top_inst/bias_top_inst/bias_0]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[0].ker_inst}
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[0].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[1].ker_inst}
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[1].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[2].ker_inst}
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[2].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[3].ker_inst}
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[3].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[4].ker_inst}
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[4].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[5].ker_inst}
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[5].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[6].ker_inst}
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[6].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[7].ker_inst}
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:12 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[7].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[8].ker_inst}
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:13 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[8].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[9].ker_inst}
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:14 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[9].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[10].ker_inst}
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:15 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[10].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[11].ker_inst}
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:16 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[11].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[12].ker_inst}
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:17 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[12].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[13].ker_inst}
set_property src_info {type:SCOPED_XDC file:18 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:18 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[13].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[14].ker_inst}
set_property src_info {type:SCOPED_XDC file:19 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:19 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[14].ker_inst}]
current_instance {FFN_top_inst/ker_top_inst/ker_bank[15].ker_inst}
set_property src_info {type:SCOPED_XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:20 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:20 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[15].ker_inst}]
current_instance FFN_top_inst/if_top_inst/if_0
set_property src_info {type:SCOPED_XDC file:21 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:21 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells FFN_top_inst/if_top_inst/if_0]
current_instance dut_addnorm/u_sqrt
set_property src_info {type:SCOPED_XDC file:22 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_ports -scoped_to_current_instance aclk]
current_instance
set_property src_info {type:SCOPED_XDC file:22 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dut_addnorm/u_sqrt]
current_instance SA_top_inst/ota01/otbf_0
set_property src_info {type:SCOPED_XDC file:23 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:23 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ota01/otbf_0]
current_instance SA_top_inst/ota01/otbf_1
set_property src_info {type:SCOPED_XDC file:24 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:24 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ota01/otbf_1]
current_instance SA_top_inst/ota01/otbf_r1_0
set_property src_info {type:SCOPED_XDC file:25 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:25 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ota01/otbf_r1_0]
current_instance SA_top_inst/ota01/otbf_r1_1
set_property src_info {type:SCOPED_XDC file:26 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:26 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ota01/otbf_r1_1]
current_instance SA_top_inst/bia01/bias_0
set_property src_info {type:SCOPED_XDC file:27 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:27 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/bia01/bias_0]
current_instance SA_top_inst/kea01/ker_0
set_property src_info {type:SCOPED_XDC file:28 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:28 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/kea01/ker_0]
current_instance SA_top_inst/kea01/ker_1
set_property src_info {type:SCOPED_XDC file:29 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:29 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/kea01/ker_1]
current_instance SA_top_inst/kea01/ker_2
set_property src_info {type:SCOPED_XDC file:30 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:30 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/kea01/ker_2]
current_instance SA_top_inst/kea01/ker_3
set_property src_info {type:SCOPED_XDC file:31 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:31 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/kea01/ker_3]
current_instance SA_top_inst/kea01/ker_4
set_property src_info {type:SCOPED_XDC file:32 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:32 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/kea01/ker_4]
current_instance SA_top_inst/kea01/ker_5
set_property src_info {type:SCOPED_XDC file:33 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:33 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/kea01/ker_5]
current_instance SA_top_inst/kea01/ker_6
set_property src_info {type:SCOPED_XDC file:34 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:34 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/kea01/ker_6]
current_instance SA_top_inst/kea01/ker_7
set_property src_info {type:SCOPED_XDC file:35 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:35 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/kea01/ker_7]
current_instance SA_top_inst/ifa01/if0bA
set_property src_info {type:SCOPED_XDC file:36 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:36 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:36 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if0bA]
current_instance SA_top_inst/ifa01/if0bB
set_property src_info {type:SCOPED_XDC file:37 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:37 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:37 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if0bB]
current_instance SA_top_inst/ifa01/if1bA
set_property src_info {type:SCOPED_XDC file:38 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:38 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:38 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if1bA]
current_instance SA_top_inst/ifa01/if1bB
set_property src_info {type:SCOPED_XDC file:39 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:39 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:39 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if1bB]
current_instance SA_top_inst/ifa01/if2bA
set_property src_info {type:SCOPED_XDC file:40 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:40 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:40 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if2bA]
current_instance SA_top_inst/ifa01/if2bB
set_property src_info {type:SCOPED_XDC file:41 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:41 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:41 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if2bB]
current_instance SA_top_inst/ifa01/if3bA
set_property src_info {type:SCOPED_XDC file:42 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:42 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:42 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if3bA]
current_instance SA_top_inst/ifa01/if3bB
set_property src_info {type:SCOPED_XDC file:43 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:43 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:43 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if3bB]
current_instance SA_top_inst/ifa01/if4bA
set_property src_info {type:SCOPED_XDC file:44 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:44 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:44 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if4bA]
current_instance SA_top_inst/ifa01/if4bB
set_property src_info {type:SCOPED_XDC file:45 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:45 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:45 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if4bB]
current_instance SA_top_inst/ifa01/if5bA
set_property src_info {type:SCOPED_XDC file:46 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:46 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:46 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if5bA]
current_instance SA_top_inst/ifa01/if5bB
set_property src_info {type:SCOPED_XDC file:47 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:47 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:47 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if5bB]
current_instance SA_top_inst/ifa01/if6bA
set_property src_info {type:SCOPED_XDC file:48 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:48 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:48 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if6bA]
current_instance SA_top_inst/ifa01/if6bB
set_property src_info {type:SCOPED_XDC file:49 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:49 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:49 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if6bB]
current_instance SA_top_inst/ifa01/if7bA
set_property src_info {type:SCOPED_XDC file:50 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:50 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:50 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if7bA]
current_instance SA_top_inst/ifa01/if7bB
set_property src_info {type:SCOPED_XDC file:51 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
set_property src_info {type:SCOPED_XDC file:51 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clkb]
current_instance
set_property src_info {type:SCOPED_XDC file:51 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells SA_top_inst/ifa01/if7bB]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells FFN_top_inst/ot_top_inst/ot_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells FFN_top_inst/pe_top_inst/blkpe_r0/q0_m0/mult_3_stage_inst1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells FFN_top_inst/pe_top_inst/blkpe_r0/q0_m0/mult_2_stage_inst0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells FFN_top_inst/bias_top_inst/bias_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[0].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[10].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[11].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[12].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[13].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[14].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[15].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[1].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[2].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[3].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[4].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[5].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[6].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[7].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[8].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {FFN_top_inst/ker_top_inst/ker_bank[9].ker_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells FFN_top_inst/if_top_inst/if_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells dut_addnorm/u_sqrt]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ota01/otbf_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ota01/otbf_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ota01/otbf_r1_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ota01/otbf_r1_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/bia01/bias_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/kea01/ker_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/kea01/ker_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/kea01/ker_2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/kea01/ker_3]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/kea01/ker_4]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/kea01/ker_5]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/kea01/ker_6]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/kea01/ker_7]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if0bA]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if0bB]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if1bA]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if1bB]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if2bA]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if2bB]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if3bA]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if3bB]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if4bA]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if4bB]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if5bA]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if5bB]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if6bA]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if6bB]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if7bA]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells SA_top_inst/ifa01/if7bB]
