# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv D:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog {
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/FFN_BRAM_OT_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/MULT_3_STAGE_32X32_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/MULT_2_STAGE_32X16_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/FFN_BRAM_BIAS_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/FFN_BRAM_KER_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/FFN_BRAM_IF_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/DW_sqrt_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/BRAM_OT_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/BRAM_BIAS_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/BRAM_KER_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/BRAM_IF_stub.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/bias_module/FFN_bias_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/bias_module/FFN_biassram_r.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/bias_module/FFN_biassram_w.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/main_ctrl/FFN_d_empn_rd_mux.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/main_ctrl/FFN_fsm64.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/main_ctrl/FFN_get_ins.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/compute_engine/FFN_getpe_result.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/compute_engine/FFN_i_gelu.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/input_module/FFN_if_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/input_module/FFN_ifsram_r.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/input_module/FFN_ifsram_w.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/kernel_module/FFN_ker_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/kernel_module/FFN_kersram_r.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/kernel_module/FFN_kersram_w.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/output_module/FFN_ot_fifo.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/output_module/FFN_ot_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/output_module/FFN_otsram_r.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/output_module/FFN_otsram_w.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/compute_engine/FFN_pe_8e.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/compute_engine/FFN_pe_array.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/compute_engine/FFN_pe_qz_pkg.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/compute_engine/FFN_pe_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/compute_engine/FFN_quan2uint8.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/compute_engine/FFN_quan2uint8_gelu.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/main_ctrl/FFN_schedule_ctrl.v
      D:/Transformer_code/Transformer_IP_Integrate/src/FFN_module/FFN_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/common_module/fifo/INPUT_STREAM_if.v
      D:/Transformer_code/Transformer_IP_Integrate/src/common_module/fifo/OUTPUT_STREAM_if.v
      D:/Transformer_code/Transformer_IP_Integrate/src/Transformer_FSM.v
      D:/Transformer_code/Transformer_IP_Integrate/src/Add_Norm_module/add.v
      D:/Transformer_code/Transformer_IP_Integrate/src/Add_Norm_module/addnormtop.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/bias_rw/bias_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/bias_rw/biassram_r.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/bias_rw/biassram_w.v
      D:/Transformer_code/Transformer_IP_Integrate/src/common_module/counter/count_yi_v4.v
      D:/Transformer_code/Transformer_IP_Integrate/src/common_module/counter/count_yi_v5.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/main_ctrl/d_empn_rd_mux.v
      D:/Transformer_code/Transformer_IP_Integrate/src/Add_Norm_module/div.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SOFTMAX_module/exp_ln2_based.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/main_ctrl/fsm64.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/main_ctrl/get_ins.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/ifmap_rw/if_dout_mux.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/ifmap_rw/if_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/ifmap_rw/ifsram_pd.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/ifmap_rw/ifsram_r.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/ifmap_rw/ifsram_w.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/ifmap_rw/ifw_cnt_fsm.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/kernel_rw/ker_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/kernel_rw/kersram_r.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/kernel_rw/kersram_w.v
      D:/Transformer_code/Transformer_IP_Integrate/src/Add_Norm_module/mean.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/output_module/ot_fifo.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/output_module/ot_read.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/output_module/ot_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/output_module/ot_write.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/compute_engine/pe_8_ver3.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/compute_engine/pe_blk64.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/compute_engine/pe_qz_pkg.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/compute_engine/pe_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SOFTMAX_module/pre_processor.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/compute_engine/re_quantize.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/compute_engine/ru_get.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/main_ctrl/schedule_ctrl.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SOFTMAX_module/softmax_top.v
      D:/Transformer_code/Transformer_IP_Integrate/src/Add_Norm_module/sub.v
      D:/Transformer_code/Transformer_IP_Integrate/src/SA_module/top_pto.v
      D:/Transformer_code/Transformer_IP_Integrate/src/Add_Norm_module/var.v
      D:/Transformer_code/Transformer_IP_Integrate/src/common_module/yolo_rst_if.v
      D:/Transformer_code/Transformer_IP_Integrate/src/Transformer_top.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/realtime/Transformer_top_synth.xdc
    rt::sdcChecksum
    set rt::top Transformer_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Transformer_code/Transformer_IP_Integrate/vivado/build/Transformer_IP/Transformer_IP.cache/wt}
    rt::set_parameter enableSplitFlowPath "D:/Transformer_code/Transformer_IP_Integrate/.Xil/Vivado-18448-LAPTOP-V9ODUN3G/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
